title: Chi Hwan's Blog
description: HEP Physics Research & Development Blog
url: "https://hepchihwan.github.io"
baseurl: ""

remote_theme: "jeffreytse/jekyll-theme-yat"

author:
  name: Chi Hwan
  email: your-email@example.com

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-spaceship

permalink: /:categories/:year/:month/:day/:title/

# Header navigation pages
header_pages:
  - categories/lrsm/index.md
  - categories/tools/index.md
  - categories/epr/index.md
  - categories/practice/index.md
  - about.md

# YAT theme configuration
yat:
  home:
    banner:
      title: "Chi Hwan's Blog"
      subtitle: "HEP Physics Research & Development"
      image: "/img/KakaoTalk_20250813_191149495.jpg"
    sidebar:
      enable: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Chi Hwan"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md