title: Chi Hwan's Blog
description: HEP Physics Research & Development Blog
url: "https://hepchihwan.github.io"
baseurl: ""

remote_theme: "jeffreytse/jekyll-theme-yat"

author:
  name: Chi Hwan
  email: your-email@example.com

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-spaceship

permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Chi Hwan"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md